saseumn/models.py
from datetime import datetime

from flask import url_for
from passlib.hash import bcrypt
from sqlalchemy.ext.hybrid import hybrid_property
from flask_security import UserMixin, RoleMixin

from saseumn.objects import login_manager
from saseumn.objects import db
from saseumn.util import random_string

attendance = db.Table("attendance", db.Model.metadata,
                      db.Column("user_id", db.Integer, db.ForeignKey("users.id")),
                      db.Column("event_id", db.Integer, db.ForeignKey("events.id")))

roles_users = db.Table("roles_users", db.Model.metadata,
                       db.Column("user_id", db.Integer(), db.ForeignKey("users.id")),
                       db.Column("role_id", db.Integer(), db.ForeignKey("roles.id")))


class Role(db.Model, RoleMixin):
    __tablename__ = "roles"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __str__(self):
        return self.name


class PasswordResetToken(db.Model):
    __tablename__ = "password_reset_tokens"

    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.Integer, db.ForeignKey("users.id"), index=True)
    active = db.Column(db.Boolean)
    token = db.Column(db.String(length=16), default=lambda: random_string(length=16))
    email = db.Column(db.Unicode(length=128))
    expire = db.Column(db.DateTime)

    @property
    def expired(self):
        return datetime.utcnow() >= self.expire

    @property
    def user(self):
        return User.get_by_id(self.uid)


class Event(db.Model):
    __tablename__ = "events"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(64))
    location = db.Column(db.Text)
    description = db.Column(db.Text)
    published = db.Column(db.Boolean, default=False)
    start_time = db.Column(db.DateTime)
    registration_key = db.Column(db.String(32), default=lambda: random_string(length=24))

    attendees = db.relationship("User", secondary=attendance, backref="events")

    @property
    def registration_link(self):
        return url_for("users.checkin", evtkey=self.registration_key, _external=True)


class Resume(db.Model):
    __tablename__ = "resumes"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(32))
    hashed = db.Column(db.Unicode(64))

    date_created = db.Column(db.DateTime, default=datetime.now)
    date_updated = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)


class ResumePermission(db.Model):
    __tablename__ = "resume_permissions"

    id = db.Column(db.Integer, primary_key=True)


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(32))
    username = db.Column(db.String(16), unique=True, index=True)
    _admin = db.Column("admin", db.Boolean, default=False)
    email = db.Column(db.String(256), unique=True, index=True)
    email_verified = db.Column(db.Boolean)
    email_verification_token = db.Column(db.String(256), index=True)
    _register_time = db.Column("register_time", db.DateTime, default=datetime.now)
    _password = db.Column("password", db.String(256))

    roles = db.relationship("Role", secondary=roles_users, backref=db.backref("users", lazy="dynamic"))
    resumes = db.relationship("Resume", backref="user", lazy=True)

    @hybrid_property
    def admin(self):
        return self._admin

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = bcrypt.encrypt(password, rounds=10)

    def check_password(self, password):
        return bcrypt.verify(password, self.password)

    @staticmethod
    @login_manager.user_loader
    def get_by_id(id):
        query_results = User.query.filter_by(id=id)
        return query_results.first()

    @property
    def is_active(self):
        return True

    @property
    def is_authenticated(self):
        return True

    def get_id(self):
        return str(self.id)

    # these are here to satisfy flask-security, we don't really need them yet
    @property
    def active(self):
        return True

    @active.setter
    def active(self, value):
        return

saseumn/__init__.py
import logging
import time
import sys

from flask import Flask, url_for
from flask_admin import helpers as admin_helpers

from saseumn.admin import SecuredHomeView, RoleView, EventView, UserView
from saseumn.config import Config
from saseumn.models import Role, User
from saseumn.objects import admin, db, init_security, login_manager


def make_app(config=None, testing=None):
    """ Returns a Flask object ready to serve the website. """

    if not config:
        if not testing:
            testing = False
        config = Config(testing=testing)

    # Create a Flask app object.
    app = Flask(__name__)
    app.config.from_object(config)

    @app.after_request
    def after_request(response):
        if app.config.get("ENVIRONMENT") == "production":
            response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
        return response

    @app.template_filter("to_timestamp")
    def to_timestamp(d):
        return int(time.mktime(d.timetuple()))

    # Initialize
    admin.init_app(app, index_view=SecuredHomeView(url="/admin"))
    db.init_app(app)
    login_manager.init_app(app)
    security = init_security(app, User, Role)

    app.db = db

    @security.context_processor
    def security_context_processor():
        return dict(
            admin_base_template=admin.base_template,
            admin_view=admin.index_view,
            h=admin_helpers,
            get_url=url_for
        )

    # Admin stuff
    admin.add_view(RoleView(db.session))
    admin.add_view(EventView(db.session))
    admin.add_view(UserView(db.session))

    # Register endpoints.
    import saseumn.views as views
    app.register_blueprint(views.base.blueprint)
    app.register_blueprint(views.users.blueprint, url_prefix="/users")

    return app


if __name__ == "__main__":
    config = Config()
    app = make_app(config)
    app.run(port=config.port)

saseumn/views/__init__.py
import saseumn.views.base
import saseumn.views.users

saseumn/views/base.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template
from sqlalchemy import and_

from saseumn.models import Event

blueprint = Blueprint("base", __name__)


@blueprint.route("/")
def index():
    upcoming = Event.query.filter(and_(Event.published, Event.start_time > datetime.now())).order_by(Event.start_time).first()
    return render_template("base/index.html", upcoming=upcoming)


@blueprint.route("/about")
def about():
    # team = [
    #     {
    #         'avatar': '/static/img/dev.jpg',
    #         'username': 'Dist',
    #         'name': 'Devin Deng',
    #         'role': 'Webmaster',
    #         'website': 'example'
    #     },
    #     {
    #         'username': 'michael',
    #         'name': 'Michael Zhang',
    #         'role': 'Webmaster',
    #         'website': 'example'
    #     }
    # ]
    return render_template("base/about.html")


@blueprint.route("/events")
def events():
    upcoming = Event.query.filter(and_(Event.published, Event.start_time > datetime.now())).order_by(Event.start_time).first()
    eventlist = Event.query.filter(and_(Event.published, Event.start_time < datetime.now())).order_by(Event.start_time.desc()).all()
    if upcoming:
        eventlist.insert(0, upcoming)
    return render_template("base/events.html", events=eventlist)

saseumn/views/users.py
import os
import string
from datetime import datetime, timedelta

from flask import (Blueprint, abort, current_app, flash, redirect,
                   render_template, request, url_for, send_file)
from flask_security import (current_user, login_required, login_user,
                            logout_user)
from flask_wtf import FlaskForm
from sqlalchemy import func, or_
from werkzeug.utils import secure_filename
from wtforms import ValidationError
from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField)
from wtforms.validators import Email, EqualTo, InputRequired, Length

from saseumn.models import Event, PasswordResetToken, Resume, User, db
from saseumn.objects import user_datastore
from saseumn.util import (VALID_USERNAME, get_redirect_target, hash_file,
                          random_string, redirect_back, send_email)

blueprint = Blueprint("users", __name__, template_folder="templates")
email_template = """
Hello, $username!

You recently created an account with SASE UMN using this email. To prove you're
legit, please click on the following link (or copy-paste it into your browser
your email client didn't render a link).

$link

Thanks!
SASE UMN Webmaster
"""


@blueprint.route("/login", methods=["GET", "POST"])
def login():
    redirect_to = get_redirect_target()
    if current_user.is_authenticated:
        return redirect_back("base.index")
    login_form = LoginForm(remember=True)
    if login_form.validate_on_submit():
        user = login_form.get_user()
        if not user.admin:
            if not current_app.config.get("EMAIL_VERIFICATION_DISABLED", False) and not user.email_verified:
                flash("You haven't activated your account yet! Check your email for an activation email.", "danger")
                return redirect(url_for("users.login"))
        login_user(user)
        flash("Successfully logged in!", "success")
        return redirect_back("base.index")
    return render_template("users/login.html", login_form=login_form, next=redirect_to)


@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Successfully logged out!", "success")
    return redirect(url_for("base.index"))


@blueprint.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("base.index"))
    register_form = RegisterForm(prefix="register")
    if register_form.validate_on_submit():
        new_user = register_user(register_form.name.data,
                                 register_form.email.data,
                                 register_form.username.data,
                                 register_form.password.data,
                                 admin=False)
        flash("Check your email for an activation link.", "info")
        return redirect(url_for("users.login"))
    return render_template("users/register.html", register_form=register_form)


@blueprint.route("/checkin/<string:evtkey>", methods=["GET", "POST"])
def checkin(evtkey):
    event = None
    if evtkey is not None:
        event = Event.query.filter_by(registration_key=evtkey).first()
    login_form = LoginForm(remember=True)
    register_form = RegisterForm(prefix="register")
    if login_form.submit.data and login_form.validate_on_submit():
        user = login_form.get_user()
        event.attendees.append(user)
        db.session.add(event)
        db.session.commit()
        flash("Thanks for checking in!", "success")
        return redirect_back("users.checkin", evtkey=evtkey)
    if register_form.submit.data and register_form.validate_on_submit():
        new_user = register_user(register_form.name.data,
                                 register_form.email.data,
                                 register_form.username.data,
                                 register_form.password.data,
                                 admin=False)
        event.attendees.append(new_user)
        db.session.add(event)
        db.session.commit()
        flash("Check your email for an activation link.", "info")
        return redirect(url_for("users.checkin", evtkey=evtkey))
    return render_template("users/checkin.html", event=event, login_form=login_form, register_form=register_form)


@blueprint.route("/password/forgot", methods=["GET", "POST"])
def forgot():
    forgot_form = PasswordForgotForm()
    if forgot_form.validate_on_submit():
        if forgot_form.user is not None:
            token = PasswordResetToken(active=True, uid=forgot_form.user.id, email=forgot_form.email.data, expire=datetime.utcnow() + timedelta(days=1))
            db.session.add(token)
            db.session.commit()
            url = url_for("users.reset", code=token.token, _external=True)
            send_email(forgot_form.email.data, "SASE UMN Account Password Reset", "Click here to reset your password: %s" % url)
        flash("If you have an email registered with us, then you should have received an email. Check your inbox now!", "success")
        return redirect(url_for("users.forgot"))
    return render_template("users/forgot.html", forgot_form=forgot_form)


@blueprint.route("/password/reset/<string:code>", methods=["GET", "POST"])
def reset(code):
    token = PasswordResetToken.query.filter_by(token=code, active=True).first()
    if not token or token.expired or token.email != token.user.email:
        redirect(url_for("base.index"))
    reset_form = PasswordResetForm()
    if reset_form.validate_on_submit():
        user = User.get_by_id(token.uid)
        user.password = reset_form.password.data
        token.active = False
        db.session.add(user)
        db.session.commit()
        flash("Password has been reset! Try logging in now.", "success")
        return redirect(url_for("users.login"))
    return render_template("users/reset.html", reset_form=reset_form)


@blueprint.route("/profile")
@blueprint.route("/profile/<int:id>")
def profile(id=None):
    if id is None and current_user.is_authenticated:
        return redirect(url_for("users.profile", id=current_user.id))
    user = User.get_by_id(id)
    if user is None:
        abort(404)
    return render_template("users/profile.html", user=user)


@blueprint.route("/resumes")
@blueprint.route("/resumes/view/<int:id>")
@login_required
def resumes(id=None):
    if id is not None:
        resume = Resume.query.get_or_404(id)
        # Prevent viewing of other people's resumes
        # TODO: make a different route allowing employers to view resumes
        if resume.user_id != current_user.id:
            return abort(403)
        path = os.path.join(current_app.config["UPLOADS_DIRECTORY"], resume.hashed)
        if not os.path.exists(path):
            return abort(404)
        return send_file(path, attachment_filename=resume.name)
    return render_template("users/resumes/index.html")


@blueprint.route("/resumes/delete/<int:id>", methods=["POST"])
@login_required
def resumes_delete(id):
    resume = Resume.query.get_or_404(id)
    if resume.user_id != current_user.id:
        return abort(403)
    db.session.delete(resume)
    db.session.commit()
    return redirect(url_for("users.resumes"))


@blueprint.route("/resumes/upload", methods=["GET", "POST"])
@login_required
def resumes_upload():
    if request.method == "POST":
        if not (request.files and "resume" in request.files):
            flash("You did not upload a resume.", "danger")
            return redirect(url_for("users.resumes_upload"))
        f = request.files["resume"]
        # TODO: validate type
        h = hash_file(f)
        f.seek(0)
        f.save(os.path.join(current_app.config["UPLOADS_DIRECTORY"], h))
        resume = Resume(name=f.filename, hashed=h, user_id=current_user.id)
        db.session.add(resume)
        db.session.commit()
        return redirect(url_for("users.resumes"))
    return render_template("users/resumes/upload.html")


@blueprint.route("/settings", methods=["GET", "POST"])
@login_required
def settings():
    change_password_form = ChangePasswordForm(prefix="change-password")
    profile_edit_form = ProfileEditForm(prefix="profile-edit")
    if change_password_form.validate_on_submit() and change_password_form.submit.data:
        current_user.password = change_password_form.password.data
        db.session.add(current_user)
        db.session.commit()
        flash("Password changed.", "success")
        return redirect(url_for("users.settings"))
    if profile_edit_form.validate_on_submit() and profile_edit_form.submit.data:
        for field in profile_edit_form:
            if hasattr(current_user, field.short_name):
                setattr(current_user, field.short_name, field.data)
        db.session.add(current_user)
        db.session.commit()
        flash("Profile updated.", "success")
        return redirect(url_for("users.settings"))
    elif not profile_edit_form.errors:
        for field in profile_edit_form:
            if hasattr(current_user, field.short_name):
                field.data = getattr(current_user, field.short_name, "")
    return render_template("users/settings.html",
                           change_password_form=change_password_form,
                           profile_edit_form=profile_edit_form)


@blueprint.route("/verify/<token>")
def verify(token):
    user = User.query.filter_by(email_verification_token=token).first()
    if user:
        if user.email_verified:
            flash("Email is already verified.", "info")
            return redirect(url_for("base.index"))
        if user.email_verification_token == token:
            user.email_verified = True
            flash("Email has been verified!", "success")
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for("base.index"))

    flash("Invalid token.", "danger")
    return redirect(url_for("users.login"))


def register_user(name, email, username, password, admin=False, **kwargs):

saseumn/templates/layout/footer.html
<footer class="site-footer site-footer--sticky">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h5 class="footer-heading">SASE UMN</h5>
                <p>
                    SASE UMN is a student organization at the University of Minnesota that is dedicated to the advancement of Asian heritage scientists and engineers in education and employment so that they can achieve their full career potential.
                </p>
                <ul class="list-inline">
                </ul>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-xs-4">
                        <h5 class="footer-heading">Useful Links</h5>
                        <ul>
                            <li><a href="{{ url_for("base.index") }}">Home</a></li>
                            <li><a href="{{ url_for("base.about") }}">About</a></li>
                            <li><a href="{{ url_for("base.events") }}">Events</a></li>
                        </ul>
                    </div>
                    <div class="col-xs-8">
                        <h5 class="footer-heading">Connect With Us</h5>
                        <p>
                            Stop by our office at 
                            <br>
                            <br>
                            Lind Hall 102<br>
                            207 Church St SE,<br>
                            Minneapolis, MN 55455
                            <br>
                            <br>
                            Or follow us on social media platforms:
                        </p>
                        <p id="links">
                            <a href="mailto:sasemail@umn.edu" target="_blank" rel="noopener"><i class="fa fa-fw fa-2x fa-envelope"></i></a>
                            <a href="https://www.facebook.com/sase.umn/" target="_blank" rel="noopener"><i class="fa fa-fw fa-2x fa-facebook-square"></i></a>
                            <a href="https://twitter.com/sase.umn/" target="_blank" rel="noopener"><i class="fa fa-fw fa-2x fa-twitter"></i></a>
                            <a href="https://www.instagram.com/saseumn/" target="_blank" rel="noopener"><i class="fa fa-fw fa-2x fa-instagram"></i></a>
                            <a href="https://www.youtube.com/user/saseumn/" target="_blank" rel="noopener"><i class="fa fa-fw fa-2x fa-youtube-play"></i></a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row footer-copyright">
            <p>
                &copy; 2017 SASE UMN. This website is open-source on <a href="https://github.com/saseumn/website" target="_blank">Github</a>.
            </p>
        </div>
</footer>

saseumn/templates/layout/head.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1">
<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-HzUaiJdCTIY/RL2vDPRGdEQHHahjzwoJJzGUkYjHVzTwXFQ2QN/nVgX7tzoMW3Ov" crossorigin="anonymous">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link href="/static/css/main.css" rel="stylesheet" />
<link href="/static/img/logo.png" rel="icon" />

saseumn/templates/layout/navbar.html
<nav class="navbar navbar-default" style="margin-bottom: 0; {% if admin_view %}background-color: #a3210b;{% endif %}">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for("base.index") }}">
                <img style="height: 24px; vertical-align: middle; display:inline-block;" src="/static/img/logo.png" />
                SASE UMN {% if admin_view %}<b>ADMIN</b>{% endif %}
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for("base.about") }}">About</a></li>
                <li><a href="{{ url_for("base.events") }}">Events</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                    {% if current_user.admin %}
                        <li><a href="{{ url_for("admin.index") }}">Admin Panel</a></li>
                    {% endif %}
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ current_user.username }}&nbsp;<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ url_for("users.profile") }}"><i class="fa fa-fw fa-user"></i> My Profile</a></li>
                            <li><a href="{{ url_for("users.resumes") }}"><i class="fa fa-fw fa-file-text"></i> My Resumes</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{{ url_for("users.settings") }}"><i class="fa fa-fw fa-sliders"></i> Account Settings</a></li>
                            <li><a href="{{ url_for("users.logout") }}"><i class="fa fa-fw fa-sign-out"></i> Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{{ url_for("users.login") }}">Login</a></li>
                    <li><a href="{{ url_for("users.register") }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>